apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webhook-demo.fullname" . }}
  labels:
    app: {{ include "webhook-demo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "webhook-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "webhook-demo.name" . }}
    spec:
      containers:
      - name: webhook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        volumeMounts:
        - name: webhook-tls
          mountPath: /etc/webhook
          readOnly: true
      volumes:
      - name: webhook-tls
        secret:
          secretName: webhook-tls
