---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-webhook-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "webhook-demo.name" . }}
    helm.sh/chart: {{ include "webhook-demo.chart" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-webhook-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-webhook-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: patch-webhook-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: patch-webhook-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-webhook-clusterrole
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-webhook-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: patch-webhook-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: patch-webhook-clusterrole
  apiGroup: rbac.authorization.k8s.io
