apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
  namespace: default
spec:
  secretName: webhook-tls  # This secret will hold the TLS cert and key
  dnsNames:
  - webhook-service.default.svc
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
